/**
 * Navigation graph enums (implementation plan §11, Appendix A), versioned with the binary format.
 * Plain const objects so the package stays erasable-syntax only.
 */
export const EdgeType = {
  /** Footway, sidewalk, path: ordinary walking surface. */
  Pavement: 0,
  Crossing: 1,
  Steps: 2,
  Elevator: 3,
  Escalator: 4,
  /** Pedestrian street or plaza outline. */
  Pedestrian: 5,
  /** Shared cycle/foot way. */
  SharedPath: 6,
  LivingStreet: 7,
  Corridor: 8,
  /** Connector joining an entrance to the network (M3). */
  Entrance: 9,
  /** A walk around a flat roof, generated at runtime (never routed through from the street). */
  Roof: 10,
} as const;
export type EdgeType = (typeof EdgeType)[keyof typeof EdgeType];

export const EdgePermission = {
  Human: 1 << 0,
  Robot: 1 << 1,
  /** Usable without steps (wheelchairs, most robots). */
  StepFree: 1 << 2,
} as const;

export const EdgeFlag = {
  Bridge: 1 << 0,
  Tunnel: 1 << 1,
  Indoor: 1 << 2,
  Covered: 1 << 3,
  /** Explicitly mapped `footway=sidewalk`. */
  Sidewalk: 1 << 4,
  /** Generated by the pipeline (sidewalk inference, crossings, connectors), not mapped in OSM. */
  Inferred: 1 << 5,
  /** Implicit crossing: a junction arm with no mapped crossing; routing charges extra. */
  Implicit: 1 << 6,
  /** Crossing controlled by traffic signals (`crossing=traffic_signals`). */
  Signalised: 1 << 7,
} as const;

export const NodeFlag = {
  /** Entrance generated on the façade nearest the network (building had none mapped). */
  SyntheticEntrance: 1 << 0,
} as const;

/** `nodes.buildingId` for nodes that belong to no building. */
export const NO_BUILDING = 0xffffffff;

export const NodeType = {
  Junction: 0,
  /** Degree-1 node: a dead end, or a way end that joins nothing. */
  End: 1,
  Entrance: 2,
  // Indoor (implementation plan §12–13). Reserved: the procedural interiors that made these were
  // removed, and the numbers stay so the binary format keeps its meaning.
  /** Ground-floor lobby: joined to the building's entrances and its core. */
  Lobby: 3,
  /** A destination zone with a capacity (office floor area, flat, shop). */
  Room: 4,
  /** Lift lobby on one floor of a core. */
  LiftLobby: 5,
  /** Stair landing on one floor of a core. */
  Stair: 6,
  /** Corridor node on a floor's spine. */
  Corridor: 7,
  /** A corner or junction of a roof walk (generated at runtime, see EdgeType.Roof). */
  Roof: 8,
} as const;
export type NodeType = (typeof NodeType)[keyof typeof NodeType];

export const BuildingType = {
  Other: 0,
  Residential: 1,
  Office: 2,
  Commercial: 3,
  Retail: 4,
  Industrial: 5,
  Public: 6,
  Transport: 7,
} as const;
export type BuildingType = (typeof BuildingType)[keyof typeof BuildingType];

export const BuildingFlag = {
  /** A `building:part`. */
  Part: 1 << 0,
  /** An outline that has parts inside it: renderers draw the parts instead. */
  HasParts: 1 << 1,
  HeightFromTag: 1 << 2,
  HeightFromLevels: 1 << 3,
  /** Height is a type default: no height or levels tag. */
  HeightDefault: 1 << 4,
  /**
   * Not a real building: a station's demand node (passengers to and from beyond the region). Not
   * drawn, never given an interior; its entrances are the station's.
   */
  Virtual: 1 << 5,
} as const;
