import type { PedestrianAttributes } from './pedestrian.ts';

/**
 * Stage 4 (implementation plan §10): pedestrian ways → a clean edge graph.
 *
 *  1. keep only segments with both ends inside the region;
 *  2. split ways at every node shared with another way (and at way ends);
 *  3. snap dangling ends to another graph node within `snapM` (near-miss junctions);
 *  4. contract degree-2 nodes whose two edges have identical attributes into one polyline;
 *  5. Douglas–Peucker simplification at `simplifyM`;
 *  6. drop connected components shorter than `minComponentM` in total, unless they hold a
 *     `keepNodes` node (entrances).
 *
 * Node ids may be negative: nodes generated by the pipeline (inferred sidewalks, connectors).
 */
export interface TopologyInput {
  /** Local position (x east, y north) of every OSM node the ways reference. */
  positions: Map<number, [number, number]>;
  ways: { id: number; refs: number[]; attributes: PedestrianAttributes }[];
  /** Region bounds in local metres. */
  bounds: { minX: number; minY: number; maxX: number; maxY: number };
  snapM?: number;
  simplifyM?: number;
  minComponentM?: number;
  /** Nodes that must survive as graph nodes (never contracted, their component never dropped). */
  keepNodes?: ReadonlySet<number>;
}

export interface GraphEdge {
  osmWayId: number;
  from: number;
  to: number;
  /** Full polyline including both end nodes, local metres. */
  points: [number, number][];
  length: number;
  attributes: PedestrianAttributes;
}

export interface Topology {
  /** Graph nodes (dense ids 0…n−1): position and the OSM node they came from. */
  nodes: { x: number; y: number; osmId: number; level: number }[];
  edges: GraphEdge[];
  qa: {
    inputWays: number;
    rawSegments: number;
    snappedEnds: number;
    contractedNodes: number;
    simplifiedPointsRemoved: number;
    components: number;
    droppedComponents: number;
    droppedLengthM: number;
    lengthM: number;
    largestComponentShare: number;
    danglingEnds: number;
    levelConflicts: number;
  };
}

interface WorkEdge {
  osmWayId: number;
  refs: number[];
  attributes: PedestrianAttributes;
  alive: boolean;
}

export function buildTopology(input: TopologyInput): Topology {
  const snapM = input.snapM ?? 0.5;
  const simplifyM = input.simplifyM ?? 0.15;
  const minComponentM = input.minComponentM ?? 30;
  const { positions, bounds } = input;
  const keepNodes = input.keepNodes ?? new Set<number>();
  const inside = (ref: number): boolean => {
    const p = positions.get(ref);
    return (
      p !== undefined &&
      p[0] >= bounds.minX &&
      p[0] <= bounds.maxX &&
      p[1] >= bounds.minY &&
      p[1] <= bounds.maxY
    );
  };

  // 1. Clip: runs of consecutive in-bounds nodes.
  const runs: { osmWayId: number; refs: number[]; attributes: PedestrianAttributes }[] = [];
  for (const way of input.ways) {
    let run: number[] = [];
    const flush = () => {
      if (run.length >= 2) runs.push({ osmWayId: way.id, refs: run, attributes: way.attributes });
      run = [];
    };
    for (const ref of way.refs) {
      if (inside(ref)) run.push(ref);
      else flush();
    }
    flush();
  }

  // 2. Split at shared nodes and run ends.
  const uses = new Map<number, number>();
  for (const run of runs) {
    run.refs.forEach((ref, i) => {
      const end = i === 0 || i === run.refs.length - 1;
      uses.set(ref, (uses.get(ref) ?? 0) + (end ? 2 : 1));
    });
  }
  const isJunction = (ref: number): boolean => (uses.get(ref) ?? 0) >= 2;
  let edges: WorkEdge[] = [];
  for (const run of runs) {
    let start = 0;
    for (let i = 1; i < run.refs.length; i++) {
      if (i === run.refs.length - 1 || isJunction(run.refs[i])) {
        const refs = dedupeConsecutive(run.refs.slice(start, i + 1));
        if (refs.length >= 2)
          edges.push({ osmWayId: run.osmWayId, refs, attributes: run.attributes, alive: true });
        start = i;
      }
    }
  }
  const rawSegments = edges.length;

  // 3. Snap dangling ends to the nearest other endpoint within snapM.
  const degree = (list: WorkEdge[]): Map<number, number> => {
    const d = new Map<number, number>();
    for (const e of list) {
      if (!e.alive) continue;
      const a = e.refs[0];
      const b = e.refs[e.refs.length - 1];
      d.set(a, (d.get(a) ?? 0) + 1);
      d.set(b, (d.get(b) ?? 0) + 1);
    }
    return d;
  };
  let deg = degree(edges);
  const grid = new Map<string, number[]>();
  const cellOf = (p: [number, number]) => `${Math.floor(p[0] / snapM)},${Math.floor(p[1] / snapM)}`;
  for (const ref of deg.keys()) {
    const p = positions.get(ref);
    if (p === undefined) continue;
    const key = cellOf(p);
    const list = grid.get(key) ?? [];
    list.push(ref);
    grid.set(key, list);
  }
  const replace = new Map<number, number>();
  let snappedEnds = 0;
  for (const [ref, d] of deg) {
    if (d !== 1 || replace.has(ref) || keepNodes.has(ref)) continue;
    const p = positions.get(ref);
    if (p === undefined) continue;
    const cx = Math.floor(p[0] / snapM);
    const cy = Math.floor(p[1] / snapM);
    let best: number | undefined;
    let bestDistance = snapM;
    for (let ox = -1; ox <= 1; ox++) {
      for (let oy = -1; oy <= 1; oy++) {
        for (const other of grid.get(`${cx + ox},${cy + oy}`) ?? []) {
          if (other === ref || replace.has(other)) continue;
          const q = positions.get(other);
          if (q === undefined) continue;
          const distance = Math.hypot(q[0] - p[0], q[1] - p[1]);
          if (distance <= bestDistance) {
            bestDistance = distance;
            best = other;
          }
        }
      }
    }
    if (best !== undefined) {
      replace.set(ref, best);
      snappedEnds++;
    }
  }
  if (replace.size > 0) {
    for (const e of edges) {
      e.refs = dedupeConsecutive(e.refs.map((r) => replace.get(r) ?? r));
      if (e.refs.length < 2) e.alive = false;
    }
  }

  // 4. Contract degree-2 nodes joining two edges with identical attributes.
  deg = degree(edges);
  const incident = new Map<number, WorkEdge[]>();
  for (const e of edges) {
    if (!e.alive) continue;
    for (const end of [e.refs[0], e.refs[e.refs.length - 1]]) {
      const list = incident.get(end) ?? [];
      list.push(e);
      incident.set(end, list);
    }
  }
  let contractedNodes = 0;
  for (const [ref, list] of incident) {
    const live = list.filter((e) => e.alive);
    if (live.length !== 2 || deg.get(ref) !== 2 || keepNodes.has(ref)) continue;
    const [a, b] = live as [WorkEdge, WorkEdge];
    if (a === b || !sameAttributes(a.attributes, b.attributes)) continue;
    const aRefs = a.refs[a.refs.length - 1] === ref ? a.refs : [...a.refs].reverse();
    const bRefs = b.refs[0] === ref ? b.refs : [...b.refs].reverse();
    if (aRefs[aRefs.length - 1] !== ref || bRefs[0] !== ref) continue;
    const merged = [...aRefs, ...bRefs.slice(1)];
    if (merged[0] === merged[merged.length - 1] && merged.length <= 3) continue; // would collapse a loop
    a.refs = merged;
    b.alive = false;
    const otherEnd = merged[merged.length - 1];
    const otherList = incident.get(otherEnd);
    if (otherList !== undefined)
      incident.set(
        otherEnd,
        otherList.map((e) => (e === b ? a : e)),
      );
    contractedNodes++;
  }
  edges = edges.filter((e) => e.alive);

  // Node table (dense ids), levels, polylines.
  const index = new Map<number, number>();
  const nodes: Topology['nodes'] = [];
  let levelConflicts = 0;
  const nodeOf = (ref: number, level: number): number => {
    let id = index.get(ref);
    if (id === undefined) {
      const p = positions.get(ref) ?? [0, 0];
      id = nodes.length;
      index.set(ref, id);
      nodes.push({ x: p[0], y: p[1], osmId: ref, level });
    } else if (nodes[id].level !== level) {
      levelConflicts++;
      nodes[id].level = Math.min(nodes[id].level, level);
    }
    return id;
  };
  let simplifiedPointsRemoved = 0;
  let graphEdges: GraphEdge[] = edges.map((e) => {
    const full = e.refs.map((r) => positions.get(r) ?? ([0, 0] as [number, number]));
    const points = simplify(full, simplifyM);
    simplifiedPointsRemoved += full.length - points.length;
    return {
      osmWayId: e.osmWayId,
      from: nodeOf(e.refs[0], e.attributes.level),
      to: nodeOf(e.refs[e.refs.length - 1], e.attributes.level),
      points,
      length: polylineLength(points),
      attributes: e.attributes,
    };
  });

  // 6. Components by union-find; drop short ones.
  const parent = nodes.map((_, i) => i);
  const find = (i: number): number => {
    while (parent[i] !== i) {
      parent[i] = parent[parent[i]];
      i = parent[i];
    }
    return i;
  };
  for (const e of graphEdges) parent[find(e.from)] = find(e.to);
  const componentLength = new Map<number, number>();
  for (const e of graphEdges)
    componentLength.set(find(e.from), (componentLength.get(find(e.from)) ?? 0) + e.length);
  const keep = new Set(
    [...componentLength].filter(([, length]) => length >= minComponentM).map(([root]) => root),
  );
  nodes.forEach((node, i) => {
    if (keepNodes.has(node.osmId)) keep.add(find(i));
  });
  const droppedLengthM = [...componentLength]
    .filter(([root]) => !keep.has(root))
    .reduce((s, [, l]) => s + l, 0);
  graphEdges = graphEdges.filter((e) => keep.has(find(e.from)));

  // Compact node ids after dropping.
  const used = new Map<number, number>();
  const kept: Topology['nodes'] = [];
  const remap = (id: number): number => {
    let next = used.get(id);
    if (next === undefined) {
      next = kept.length;
      used.set(id, next);
      kept.push(nodes[id]);
    }
    return next;
  };
  for (const e of graphEdges) {
    e.from = remap(e.from);
    e.to = remap(e.to);
  }

  const lengthM = graphEdges.reduce((s, e) => s + e.length, 0);
  const largest = Math.max(
    0,
    ...[...componentLength].filter(([root]) => keep.has(root)).map(([, l]) => l),
  );
  const finalDegree = new Array<number>(kept.length).fill(0);
  for (const e of graphEdges) {
    finalDegree[e.from]++;
    finalDegree[e.to]++;
  }

  return {
    nodes: kept,
    edges: graphEdges,
    qa: {
      inputWays: input.ways.length,
      rawSegments,
      snappedEnds,
      contractedNodes,
      simplifiedPointsRemoved,
      components: keep.size,
      droppedComponents: componentLength.size - keep.size,
      droppedLengthM,
      lengthM,
      largestComponentShare: lengthM > 0 ? largest / lengthM : 0,
      danglingEnds: finalDegree.filter((d) => d === 1).length,
      levelConflicts,
    },
  };
}

function sameAttributes(a: PedestrianAttributes, b: PedestrianAttributes): boolean {
  return (
    a.type === b.type &&
    a.permissions === b.permissions &&
    a.flags === b.flags &&
    a.widthCm === b.widthCm &&
    a.level === b.level
  );
}

function dedupeConsecutive(refs: number[]): number[] {
  return refs.filter((r, i) => i === 0 || r !== refs[i - 1]);
}

export function polylineLength(points: readonly [number, number][]): number {
  let length = 0;
  for (let i = 1; i < points.length; i++) {
    length += Math.hypot(points[i][0] - points[i - 1][0], points[i][1] - points[i - 1][1]);
  }
  return length;
}

/** Douglas–Peucker, keeping both ends. */
export function simplify(points: [number, number][], tolerance: number): [number, number][] {
  if (points.length <= 2) return points;
  const keep = new Uint8Array(points.length);
  keep[0] = 1;
  keep[points.length - 1] = 1;
  const stack: [number, number][] = [[0, points.length - 1]];
  for (let top = stack.pop(); top !== undefined; top = stack.pop()) {
    const [first, last] = top;
    let worst = -1;
    let worstDistance = tolerance;
    for (let i = first + 1; i < last; i++) {
      const d = distanceToSegment(points[i], points[first], points[last]);
      if (d > worstDistance) {
        worstDistance = d;
        worst = i;
      }
    }
    if (worst >= 0) {
      keep[worst] = 1;
      stack.push([first, worst], [worst, last]);
    }
  }
  return points.filter((_, i) => keep[i] === 1);
}

function distanceToSegment(p: [number, number], a: [number, number], b: [number, number]): number {
  const dx = b[0] - a[0];
  const dy = b[1] - a[1];
  const lengthSq = dx * dx + dy * dy;
  const t =
    lengthSq === 0
      ? 0
      : Math.max(0, Math.min(1, ((p[0] - a[0]) * dx + (p[1] - a[1]) * dy) / lengthSq));
  return Math.hypot(p[0] - (a[0] + t * dx), p[1] - (a[1] + t * dy));
}
