import {
  type AggregatedStep,
  aggregate,
  bytesPerAgent,
  maxAgentsAt,
  type RunRecord,
  type Spread,
} from './aggregate.ts';
import type { MatrixEntry } from './matrix.ts';

export interface SimBenchResult {
  agents: number;
  workers: number;
  avoidance: boolean;
  tickMs: { p50: number; p95: number; mean: number };
  eventsPerTick: number;
  realtimeFactor: number;
}

export interface ReportInput {
  machine: string;
  createdAt: string;
  environment: {
    cpu: string;
    memoryGb: number;
    os: string;
    browser: string;
    adapter: string;
    canvas: string;
  };
  repetitions: number;
  matrix: readonly MatrixEntry[];
  runs: readonly RunRecord[];
  /** Q8 results from tools/sim-bench, when available. */
  simBench: readonly SimBenchResult[] | null;
  decisions: readonly { file: string; title: string }[];
  rawFile: string;
}

/**
 * The Stage 0 report (step 0.11): per-question answers derived from the matrix, then every entry's
 * table. Numbers are medians across repetitions with the min–max range in brackets.
 */
export function buildReport(input: ReportInput): string {
  const data = aggregate(input.runs);
  const steps = (id: string): AggregatedStep[] => data.get(id) ?? [];
  const at = (id: string, agents: number): AggregatedStep | undefined =>
    steps(id).find((step) => step.agents === agents);
  const kept = input.runs.filter((run) => run.result !== null);
  const discarded = input.runs.filter((run) => run.error?.startsWith('disturbed') === true);
  const failed = input.runs.filter((run) => run.result === null && !discarded.includes(run));
  const entriesRun = new Set(input.runs.map((run) => run.entryId)).size;
  const loads = kept.flatMap((run) => [run.loadBefore, run.loadAfter]);
  const maxLoad = loads.length === 0 ? 0 : Math.max(...loads);
  /** Largest agent count at `fps` for an entry, or "not measured" when it has no data. */
  const capacityAt = (id: string, fps: number): string =>
    steps(id).length === 0 ? 'not measured' : fmtAgents(maxAgentsAt(steps(id), fps));

  const lines: string[] = [];
  const push = (...text: string[]) => lines.push(...text);

  push(
    `# Stage 0 benchmark report · ${input.machine}`,
    '',
    `Generated by \`tools/bench-runner\` on ${input.createdAt.slice(0, 10)} from ${kept.length} runs ` +
      `(${entriesRun} of ${input.matrix.length} matrix entries × ${input.repetitions} repetitions` +
      (failed.length > 0 ? `; ${failed.length} failed` : '') +
      `${discarded.length > 0 ? `; ${discarded.length} discarded because other work raised the machine load mid-run, and redone` : ''}). ` +
      `Every number is the **median across repetitions** with the [min–max] range; frame time is the per-run **mean** frame interval (1000 / fps), the throughput measure. ` +
      `Raw results: [\`${input.rawFile}\`](${input.rawFile}).`,
    '',
    '| | |',
    '| --- | --- |',
    `| CPU | ${input.environment.cpu}, ${input.environment.memoryGb} GB |`,
    `| OS | ${input.environment.os} |`,
    `| Browser | ${input.environment.browser} (headless; lab runs with \`--disable-frame-rate-limit --disable-gpu-vsync\`) |`,
    `| GPU adapter | ${input.environment.adapter} |`,
    `| Canvas | ${input.environment.canvas} |`,
    `| Load average during kept runs | max ${maxLoad.toFixed(1)} (runs start only below the limit; runs that end above 1.5× it are discarded and redone) |`,
    '',
    'Reproduce: `yarn workspace @city/bench-runner matrix` (full matrix, ~30 min), then',
    '`yarn workspace @city/sim-bench bench --out …` for Q8.',
    '',
    "## Answers to the plan's questions (§I.2)",
    '',
    '| # | Question | Answer from this run |',
    '| --- | --- | --- |',
  );

  const bXbot = steps('b-xbot-1k');
  const aXbot = steps('a-xbot');
  const q1 =
    bXbot.length === 0 && aXbot.length === 0
      ? 'not measured'
      : `Path B draws ${capacityAt('b-xbot-1k', 60)} X Bots (~1k tris, one LOD) at ≥ 60 fps from one baked walk; Path A (mixer per character) manages ${capacityAt('a-xbot', 60)}.`;
  const rigid = at('b-robots-rigid', 20000);
  const authored = at('b-robots-authored', 20000);
  const mixed = at('b-mixed', 1_000_000);
  const q2 =
    rigid !== undefined && authored !== undefined
      ? `Same kernels and shaders; robots differ only in data. Rigid 1-influence skinning: ${ms(rigid.frameMs)} vs ${ms(authored.frameMs)} authored (20k robots at LOD0). Mixed crowd with 25% robots at 1M: ${fps(mixed?.fps)}.`
      : 'not measured';
  const q3 =
    'Yes: per-agent `phase0` plus distance-driven phase; the WGSL integrate kernel matches the CPU reference on 4,096 agents with 0 frame mismatches (Path C self-test).';
  const briefMillion = at('b-brief', 1_000_000);
  const q4 =
    briefMillion === undefined
      ? 'Yes by construction: all LODs and impostors read the same bone buffer and pose (not measured in this run).'
      : `Yes: all LODs and impostors read the same bone buffer and pose; at 1M agents (brief) the visible split LOD0–4/impostor is ${lodSplit(briefMillion.lodVisible)}.`;
  const q5 = `≥ 60 fps: brief ${capacityAt('b-brief', 60)}, density ${capacityAt('b-density', 60)}; ≥ 30 fps: brief ${capacityAt('b-brief', 30)}, density ${capacityAt('b-density', 30)} (2 bases, tints, impostors; the largest measured step is 1M).`;
  const perAgent = bytesPerAgent(steps('b-density'));
  const q6 =
    perAgent === null
      ? 'not measured'
      : `${perAgent.toFixed(0)} B of GPU memory per agent (slope 10k → 1M, density preset; plan estimate §21: ~24 B record + derived buffers). CPU simulation state: 32 B per agent.`;
  const densityMillion = at('b-density', 1_000_000);
  const q7 =
    briefMillion !== undefined && densityMillion !== undefined
      ? `Density thresholds (LOD switches ≈ 1 px per triangle, impostors below 20 px) cost ${ms(densityMillion.frameMs)} at 1M vs ${ms(briefMillion.frameMs)} for the brief's bands. Recommend density for throughput, brief where near-field detail matters; a visual review at 1080p decides.`
      : 'not measured';
  const simMillion = input.simBench?.find(
    (r) => r.agents === 1_000_000 && r.workers === 1 && !r.avoidance,
  );
  const simNear = input.simBench?.find(
    (r) => r.agents === 1_000_000 && r.workers === 1 && r.avoidance,
  );
  const q8 =
    simMillion === undefined
      ? 'run tools/sim-bench'
      : `Not at 1M: one worker ticks 1M agents in ${simMillion.tickMs.p50.toFixed(2)} ms per 50 ms tick (${simMillion.realtimeFactor.toFixed(0)}× real time); near-tier avoidance for ~5k agents raises it to ${simNear?.tickMs.p50.toFixed(2) ?? '?'} ms.`;
  const lod0 = at('b-lod0', 10000);
  const q9 =
    lod0 === undefined
      ? 'not measured'
      : `GPU-bound: ${(lod0.triangles.median / 1e6).toFixed(0)} M skinned triangles (10k agents forced to LOD0) take ${ms(lod0.frameMs)} per frame at display rate (vsync-quantised; GPU pass ${lod0.gpuMs === null ? '—' : ms(lod0.gpuMs)}), about ${(lod0.triangles.median / 1e6 / (lod0.gpuMs?.median ?? lod0.frameMs.median)).toFixed(1)} M triangles per ms. The §17 budget of 10–12 M character triangles is ≈ ${(11 / (lod0.triangles.median / 1e6 / (lod0.gpuMs?.median ?? lod0.frameMs.median))).toFixed(1)} ms.`;
  const tFull = at('transfer-full', 1_000_000);
  const tRanges = at('transfer-ranges', 1_000_000);
  const tEvents = at('transfer-events', 1_000_000);
  const q10 =
    tEvents === undefined
      ? 'not measured'
      : `Event upload + GPU dead reckoning: at 1M agents (60 Hz, ~${extra(tEvents, 'dirty', 0)} changed records per frame) ${extra(tEvents, 'uploadCpuMs')} ms CPU, ${kib(tEvents, 'uploadBytes')} and ${extra(tEvents, 'writeCalls', 0)} write calls per frame` +
        (tRanges === undefined
          ? ''
          : `; dirty ranges cost the same CPU (${extra(tRanges, 'uploadCpuMs')} ms) but need ${extra(tRanges, 'writeCalls', 0)} write calls, because changed agents are scattered`) +
        (tFull === undefined
          ? ''
          : `; full per-frame uploads take ${extra(tFull, 'uploadCpuMs')} ms and ${kib(tFull, 'uploadBytes')} (${fps(tFull.fps)})`) +
        '. See decision 0002.';
  const pathB = at('b-density', 1_000_000);
  const pathC = at('c-density', 1_000_000);
  const q30 =
    pathB !== undefined && pathC !== undefined
      ? `Three.js vs raw WebGPU at 1M (density): ${ms(pathB.frameMs)} vs ${ms(pathC.frameMs)}. See decision 0001.`
      : 'not measured';

  for (const [q, question, answer] of [
    ['Q1', 'One skeleton animation driving many humans?', q1],
    ['Q2', 'Optimus on the same architecture?', q2],
    ['Q3', 'Independent animation phases?', q3],
    ['Q4', 'LOD meshes sharing animation state?', q4],
    ['Q5', 'How many animated humanoids on this hardware?', q5],
    ['Q6', 'Memory cost per agent?', q6],
    ['Q7', 'LOD switch distances?', q7],
    ['Q8', 'When does CPU simulation bottleneck?', q8],
    ['Q9', 'When does GPU skinning bottleneck?', q9],
    ['Q10', 'Worker → CPU → GPU transfer design?', q10],
    ['§30', 'Three.js or custom WebGPU?', q30],
  ] as const) {
    push(`| ${q} | ${question} | ${answer} |`);
  }

  push('', '## Matrix results', '');
  for (const entry of input.matrix) {
    const rows = steps(entry.id);
    push(
      `### ${entry.title}`,
      '',
      `\`${entry.id}\` · ${entry.questions.join(', ') || 'baseline'}${entry.capped === true ? ' · display-paced (60 Hz)' : ''}`,
      '',
    );
    if (rows.length === 0) {
      const errors = input.runs.filter(
        (run) => run.entryId === entry.id && run.error !== undefined,
      );
      push(
        `No successful runs.${errors[0]?.error !== undefined ? ` First error: ${errors[0].error}` : ''}`,
        '',
      );
      continue;
    }
    if (entry.id.startsWith('transfer-')) {
      push(
        '| Agents | FPS | Upload / frame | Upload CPU ms | Write calls | Dirty / frame | GPU compute ms |',
        '| ---: | ---: | ---: | ---: | ---: | ---: | ---: |',
      );
      for (const row of rows) {
        push(
          `| ${row.agents.toLocaleString('en-GB')} | ${num(row.fps, 1)} | ${kib(row, 'uploadBytes')} | ${extraSpread(row, 'uploadCpuMs')} | ${extra(row, 'writeCalls', 0)} | ${extra(row, 'dirty', 0)} | ${row.gpuMs === null ? '—' : num(row.gpuMs, 2)} |`,
        );
      }
    } else {
      push(
        '| Agents | FPS | Frame ms | CPU ms | Triangles | Draws | GPU memory | Visible LOD0–4 / impostor |',
        '| ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |',
      );
      for (const row of rows) {
        push(
          `| ${row.agents.toLocaleString('en-GB')} | ${num(row.fps, 1)} | ${num(row.frameMs, 2)} | ${num(row.cpuMs, 2)} | ${millions(row.triangles.median)} | ${row.drawCalls} | ${(row.gpuBytes.median / 2 ** 20).toFixed(0)} MiB | ${lodSplit(row.lodVisible)} |`,
        );
      }
    }
    push('');
  }

  if (input.simBench !== null) {
    push(
      '## Q8 · CPU simulation (tools/sim-bench)',
      '',
      '| Agents | Workers | Avoidance | Tick p50 ms | Tick p95 ms | Events / tick | × real time |',
      '| ---: | ---: | --- | ---: | ---: | ---: | ---: |',
    );
    for (const r of input.simBench) {
      push(
        `| ${r.agents.toLocaleString('en-GB')} | ${r.workers} | ${r.avoidance ? 'on' : 'off'} | ${r.tickMs.p50.toFixed(2)} | ${r.tickMs.p95.toFixed(2)} | ${r.eventsPerTick.toFixed(0)} | ${r.realtimeFactor.toFixed(0)}× |`,
      );
    }
    push('');
  }

  push('## Decision log', '');
  for (const decision of input.decisions) push(`- [${decision.title}](${decision.file})`);
  push(
    '',
    '## Caveats',
    '',
    '- Headless Chrome; a visible window adds compositor cost.',
    '- CPU times of GPU-bound runs include time blocked on the GPU; compare throughput by frame time.',
    '- GPU timestamps measure pass latency on a tile-based GPU and can exceed the frame interval;',
    '  they are used only for display-paced runs (Q9, transfer), where frame time is vsync-quantised.',
    '- Multi-worker avoidance rows of Q8 are optimistic (agents are partitioned by id, so each worker',
    '  sees only its own neighbours); the single-worker rows are exact.',
    '- Methodology decisions (mean frame time, display-paced GPU-saturated scenes, load guard):',
    '  decision 0003.',
    '- Placeholder assets (X Bot, Soldier, RobotExpressive); triangle-driven costs will change with',
    '  authored LODs.',
    '',
  );
  return lines.join('\n');
}

function num(value: Spread | undefined, digits: number): string {
  if (value === undefined || !Number.isFinite(value.median)) return '—';
  if (value.n <= 1 || value.min === value.max) return value.median.toFixed(digits);
  return `${value.median.toFixed(digits)} [${value.min.toFixed(digits)}–${value.max.toFixed(digits)}]`;
}

function ms(value: Spread): string {
  return `${num(value, 2)} ms`;
}

function fps(value: Spread | undefined): string {
  return value === undefined ? '—' : `${value.median.toFixed(0)} fps`;
}

function fmtAgents(value: number | null): string {
  return value === null ? 'fewer than the smallest step' : value.toLocaleString('en-GB');
}

function millions(value: number): string {
  return value >= 1e6 ? `${(value / 1e6).toFixed(1)} M` : Math.round(value).toLocaleString('en-GB');
}

function extra(step: AggregatedStep | undefined, name: string, digits = 2): string {
  const value = step?.extras[name];
  return value === undefined || !Number.isFinite(value.median) ? '—' : value.median.toFixed(digits);
}

function extraSpread(step: AggregatedStep, name: string): string {
  return num(step.extras[name], 3);
}

function kib(step: AggregatedStep | undefined, name: string): string {
  const value = step?.extras[name]?.median;
  if (value === undefined || !Number.isFinite(value)) return '—';
  return value >= 2 ** 20
    ? `${(value / 2 ** 20).toFixed(1)} MiB`
    : `${(value / 1024).toFixed(1)} KiB`;
}

function lodSplit(values: number[] | null | undefined): string {
  if (values === null || values === undefined) return '—';
  return values.map((v) => Math.round(v).toLocaleString('en-GB')).join(' / ');
}
